# This workflow will build a Golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          src/go/pkg/mod
          src/go.sum
        key: ${{ runner.os }}-go-${{ hashFiles('src/**/go.mod') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Ensure go.sum is created and up-to-date
      working-directory: src
      run: go mod tidy

    - name: Build
      working-directory: src
      run: go build -v ./...

    - name: Test
      working-directory: src
      run: go test -v ./...
